framework:
    messenger:
        transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
             'App\Component\OfferComponent\Messenger\StartSynchronizationMessage': async
