parameters:
    cityads.uri: "%env(CITY_ADS_URI)%"
    cityads.api.perpage: 100
    cityads.api.max_retries: 3
    storage.batch_size: 100

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Component\OfferComponent\Interfaces\Client\ExternalOfferApiClientInterface:
        class: App\Component\OfferComponent\Client\CityAdsApiClient
        arguments:
            $baseUri: "%cityads.uri%"

    App\Component\OfferComponent\Storage\OfferStorage:
        class: App\Component\OfferComponent\Storage\OfferStorage
        arguments:
            $batchSize: "%storage.batch_size%"

    App\Component\OfferComponent\Service\OfferSyncService:
        class: App\Component\OfferComponent\Service\OfferSyncService
        arguments:
            $apiPerPage: "%cityads.api.perpage%"
            $retryMaxAttempts: "%cityads.api.max_retries%"

    App\Exception\ExceptionListener:
        tags: [ kernel.event_listener ]
